wandb_version: 1

batch_size:
  desc: null
  value: 100
epochs:
  desc: null
  value: 5
hidden_dim:
  desc: null
  value: 400
latent_dim:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.0001
optimizer:
  desc: null
  value: adam
x_dim:
  desc: null
  value: 784
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704489657.027172
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      - 37
      4: 3.11.5
      5: 0.15.0
      8:
      - 4
      - 5
