wandb_version: 1

batch_size:
  desc: null
  value: 16
x_dim:
  desc: null
  value: 784
hidden_dim:
  desc: null
  value: 400
latent_dim:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704488362.137499
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.15.0
      8:
      - 4
      - 5
