wandb_version: 1

epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.002
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704489530.444641
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.11.5
      5: 0.15.0
      8:
      - 4
      - 5
